language: node_js  #设置语言

node_js: stable  #设置相应的版本

cache:
  directories:
    - node_modules

install:
  - npm install  #安装hexo及插件

before_script:
  - git clone --branch site https://github.com/pingeek007/pingeek007.github.io.git public

script:
  - hexo cl
  - hexo g  #生成

after_script:
  - cd ./public
  - git init
  - git config user.name "pingeek007"  #修改name
  - git config user.email "pingeek007@gmail.com"  #修改email
  - git add .
  - git commit -m "update by Travis-CI"
  - git push --force --quiet "https://${TOKEN}@${GH_REF}" master:master  #GH_TOKEN是在Travis中配置token的名称

branches:
  only:
    - site  #只监测site分支

env:
 global:
   - GH_REF: github.com/pingeek007/pingeek007.github.io.git  #设置GH_REF，注意更改yourname